from enum import StrEnum


class BtmmDirection(StrEnum):
    BULLISH_BTMM = "BULLISH_BTMM"
    BEARISH_BTMM = "BEARISH_BTMM"


class BtmmGateStatus(StrEnum):
    PENDING = "PENDING"
    PASS = "PASS"
    FAIL = "FAIL"


class BtmmContextAlignmentStatus(StrEnum):
    PENDING = "PENDING"
    ALIGNED = "ALIGNED"
    MISALIGNED = "MISALIGNED"
    UNKNOWN = "UNKNOWN"


class BtmmSessionStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    UNKNOWN = "UNKNOWN"


class BtmmInteractionClass(StrEnum):
    EDGE_TOUCH = "EDGE_TOUCH"
    PARTIAL_ENTRY = "PARTIAL_ENTRY"
    DEEP_ENTRY = "DEEP_ENTRY"
    FAR_BOUNDARY_TOUCH = "FAR_BOUNDARY_TOUCH"
    CONTROLLED_OVERSHOOT = "CONTROLLED_OVERSHOOT"
    EXCESSIVE_OVERSHOOT = "EXCESSIVE_OVERSHOOT"
    NO_CONTACT = "NO_CONTACT"
    NEAR_MISS = "NEAR_MISS"
    NONCANONICAL_SIDE_INTERACTION = "NONCANONICAL_SIDE_INTERACTION"


class BtmmReactionClassification(StrEnum):
    AWAITING_REACTION = "AWAITING_REACTION"
    REACTION_IN_PROGRESS = "REACTION_IN_PROGRESS"
    WEAK_REACTION = "WEAK_REACTION"
    STANDARD_REACTION = "STANDARD_REACTION"
    STRONG_REACTION = "STRONG_REACTION"


class BtmmLiquidityLocation(StrEnum):
    LIQUIDITY_BEFORE_POI = "LIQUIDITY_BEFORE_POI"
    LIQUIDITY_WITHIN_POI = "LIQUIDITY_WITHIN_POI"
    LIQUIDITY_AFTER_POI = "LIQUIDITY_AFTER_POI"
    MULTIPLE_LOCATIONS = "MULTIPLE_LOCATIONS"
    NONE_OBSERVED = "NONE_OBSERVED"
    NOT_YET_EVALUATED = "NOT_YET_EVALUATED"


class BtmmEvidenceSource(StrEnum):
    EXPERT_LABELLED = "EXPERT_LABELLED"
    RULE_BASED = "RULE_BASED"
    MODEL_PROPOSED = "MODEL_PROPOSED"
    HYBRID_REVIEWED = "HYBRID_REVIEWED"
    RULE_BASED_REVIEWED = "RULE_BASED_REVIEWED"


class BtmmLifecycleStatus(StrEnum):
    BTMM_CANDIDATE = "BTMM_CANDIDATE"
    BTMM_FORMING = "BTMM_FORMING"
    BTMM_BLOCKED = "BTMM_BLOCKED"
    BTMM_CONFIRMED = "BTMM_CONFIRMED"
    BTMM_CANCELLED = "BTMM_CANCELLED"


class BtmmFormationStage(StrEnum):
    CONTEXT_CHECK = "CONTEXT_CHECK"
    LIQUIDITY_MONITORING = "LIQUIDITY_MONITORING"
    APPROACH_MONITORING = "APPROACH_MONITORING"
    POI_INTERACTION = "POI_INTERACTION"
    REACTION_MONITORING = "REACTION_MONITORING"
    FINAL_GATE_EVALUATION = "FINAL_GATE_EVALUATION"


class BtmmLifecycleTransitionType(StrEnum):
    ENTERED_FORMING = "ENTERED_FORMING"
    ACCURACY_GATE_CONFIRMED = "ACCURACY_GATE_CONFIRMED"
    INTERACTION_INELIGIBLE = "INTERACTION_INELIGIBLE"
    REACTION_GATE_CONFIRMED = "REACTION_GATE_CONFIRMED"
    WEAK_REACTION = "WEAK_REACTION"
    REACTION_SPEED_GATE_CONFIRMED = "REACTION_SPEED_GATE_CONFIRMED"
    REACTION_SPEED_FAILED = "REACTION_SPEED_FAILED"
    BLOCKED = "BLOCKED"
    RESUMED_FORMING = "RESUMED_FORMING"
    CONFIRMED = "CONFIRMED"
    POI_REJECTED = "POI_REJECTED"
    CONTEXT_REJECTED = "CONTEXT_REJECTED"
    SESSION_INACTIVE = "SESSION_INACTIVE"
    VOLUME_PILLAR_FAILED = "VOLUME_PILLAR_FAILED"
    NO_LIQUIDITY_EVIDENCE = "NO_LIQUIDITY_EVIDENCE"


class BtmmCancellationReason(StrEnum):
    POI_REJECTED = "POI_REJECTED"
    INTERACTION_INELIGIBLE = "INTERACTION_INELIGIBLE"
    WEAK_REACTION = "WEAK_REACTION"
    REACTION_SPEED_FAILED = "REACTION_SPEED_FAILED"
    CONTEXT_REJECTED = "CONTEXT_REJECTED"
    SESSION_INACTIVE = "SESSION_INACTIVE"
    VOLUME_PILLAR_FAILED = "VOLUME_PILLAR_FAILED"
    NO_LIQUIDITY_EVIDENCE = "NO_LIQUIDITY_EVIDENCE"


class BtmmBlockedReason(StrEnum):
    CONTEXT_UNKNOWN = "CONTEXT_UNKNOWN"
    LIQUIDITY_REVIEW_PENDING = "LIQUIDITY_REVIEW_PENDING"
    VOLUME_REVIEW_PENDING = "VOLUME_REVIEW_PENDING"
    FORMATION_TIMEFRAME_NOT_CONFIRMED = "FORMATION_TIMEFRAME_NOT_CONFIRMED"


class BtmmVolumePillarStatus(StrEnum):
    PENDING = "PENDING"
    SUPPORTS = "SUPPORTS"
    FAILS = "FAILS"
    MISSING_DATA = "MISSING_DATA"
    UNRESOLVED = "UNRESOLVED"


class BtmmLiquidityEvidenceStatus(StrEnum):
    PENDING = "PENDING"
    PRESENT = "PRESENT"
