from enum import StrEnum


class PoiFamily(StrEnum):
    VOLUME = "VOLUME"
    PRICE_ACTION = "PRICE_ACTION"
    STRUCTURAL = "STRUCTURAL"


class PoiDirection(StrEnum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"


class PoiType(StrEnum):
    BUY_ORDER_BLOCK = "BUY_ORDER_BLOCK"
    SELL_ORDER_BLOCK = "SELL_ORDER_BLOCK"
    BUY_FAIR_VALUE_GAP = "BUY_FAIR_VALUE_GAP"
    SELL_FAIR_VALUE_GAP = "SELL_FAIR_VALUE_GAP"
    BUY_TO_SELL_CANDLE = "BUY_TO_SELL_CANDLE"
    SELL_TO_BUY_CANDLE = "SELL_TO_BUY_CANDLE"
    BASE_RALLY = "BASE_RALLY"
    BASE_DROP = "BASE_DROP"
    BULLISH_PRESSURE_WICK = "BULLISH_PRESSURE_WICK"
    BEARISH_PRESSURE_WICK = "BEARISH_PRESSURE_WICK"
    BULLISH_ENGULFING = "BULLISH_ENGULFING"
    BEARISH_ENGULFING = "BEARISH_ENGULFING"
    HAMMER = "HAMMER"
    SHOOTING_STAR = "SHOOTING_STAR"
    MORNING_STAR = "MORNING_STAR"
    EVENING_STAR = "EVENING_STAR"
    SUPPORT_ZONE = "SUPPORT_ZONE"
    RESISTANCE_ZONE = "RESISTANCE_ZONE"
    EQUAL_HIGHS_LIQUIDITY = "EQUAL_HIGHS_LIQUIDITY"
    EQUAL_LOWS_LIQUIDITY = "EQUAL_LOWS_LIQUIDITY"
    PREVIOUS_DAY_HIGH = "PREVIOUS_DAY_HIGH"
    PREVIOUS_DAY_LOW = "PREVIOUS_DAY_LOW"
    PREVIOUS_WEEK_HIGH = "PREVIOUS_WEEK_HIGH"
    PREVIOUS_WEEK_LOW = "PREVIOUS_WEEK_LOW"
    PREVIOUS_MONTH_HIGH = "PREVIOUS_MONTH_HIGH"
    PREVIOUS_MONTH_LOW = "PREVIOUS_MONTH_LOW"
    CURRENT_DAY_HIGH = "CURRENT_DAY_HIGH"
    CURRENT_DAY_LOW = "CURRENT_DAY_LOW"
    CURRENT_WEEK_HIGH = "CURRENT_WEEK_HIGH"
    CURRENT_WEEK_LOW = "CURRENT_WEEK_LOW"
    CURRENT_MONTH_HIGH = "CURRENT_MONTH_HIGH"
    CURRENT_MONTH_LOW = "CURRENT_MONTH_LOW"


class PoiStrengthTier(StrEnum):
    STANDARD = "STANDARD"
    STRONG = "STRONG"


class PoiLifecycleStatus(StrEnum):
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NO_BREACH = "NO_BREACH"
    CLOSE_BREACH_CANDIDATE = "CLOSE_BREACH_CANDIDATE"
    RECLAIM_PENDING = "RECLAIM_PENDING"
    RECLAIM_CONFIRMED = "RECLAIM_CONFIRMED"
    DISPLACEMENT_PENDING = "DISPLACEMENT_PENDING"
    DISPLACEMENT_AFTER_RECLAIM_CONFIRMED = "DISPLACEMENT_AFTER_RECLAIM_CONFIRMED"
    RECLAIM_WITHOUT_DISPLACEMENT = "RECLAIM_WITHOUT_DISPLACEMENT"
    RECLAIM_FAILED = "RECLAIM_FAILED"
    FALSE_INVALIDATION_CONFIRMED = "FALSE_INVALIDATION_CONFIRMED"
    GENUINE_INVALIDATION_CONFIRMED = "GENUINE_INVALIDATION_CONFIRMED"


class PoiLifecycleTransitionType(StrEnum):
    CLOSE_BREACH_CANDIDATE = "CLOSE_BREACH_CANDIDATE"
    RECLAIM_PENDING = "RECLAIM_PENDING"
    RECLAIM_CONFIRMED = "RECLAIM_CONFIRMED"
    DISPLACEMENT_PENDING = "DISPLACEMENT_PENDING"
    DISPLACEMENT_AFTER_RECLAIM_CONFIRMED = "DISPLACEMENT_AFTER_RECLAIM_CONFIRMED"
    RECLAIM_WITHOUT_DISPLACEMENT = "RECLAIM_WITHOUT_DISPLACEMENT"
    RECLAIM_FAILED = "RECLAIM_FAILED"
    FALSE_INVALIDATION_CONFIRMED = "FALSE_INVALIDATION_CONFIRMED"
    GENUINE_INVALIDATION_CONFIRMED = "GENUINE_INVALIDATION_CONFIRMED"


class PoiFreshnessStatus(StrEnum):
    FRESH = "FRESH"
    INTERACTED = "INTERACTED"


class PoiTapClassification(StrEnum):
    INITIAL_TAP = "INITIAL_TAP"
    REPEATED_TAP = "REPEATED_TAP"
    MULTIPLE_REPEATED_TAPS = "MULTIPLE_REPEATED_TAPS"


class PoiOverlapRelationshipType(StrEnum):
    OVERLAPPING = "OVERLAPPING"
    CONTAINS = "CONTAINS"
    CONTAINED_BY = "CONTAINED_BY"
    BOUNDARY_TOUCHING = "BOUNDARY_TOUCHING"


LIFECYCLE_ELIGIBLE_POI_TYPES: frozenset[PoiType] = frozenset(
    {
        PoiType.BUY_ORDER_BLOCK,
        PoiType.SELL_ORDER_BLOCK,
        PoiType.BUY_FAIR_VALUE_GAP,
        PoiType.SELL_FAIR_VALUE_GAP,
        PoiType.BUY_TO_SELL_CANDLE,
        PoiType.SELL_TO_BUY_CANDLE,
        PoiType.BASE_RALLY,
        PoiType.BASE_DROP,
        PoiType.BULLISH_PRESSURE_WICK,
        PoiType.BEARISH_PRESSURE_WICK,
        PoiType.BULLISH_ENGULFING,
        PoiType.BEARISH_ENGULFING,
        PoiType.HAMMER,
        PoiType.SHOOTING_STAR,
        PoiType.MORNING_STAR,
        PoiType.EVENING_STAR,
        PoiType.SUPPORT_ZONE,
        PoiType.RESISTANCE_ZONE,
    }
)

NOT_APPLICABLE_LIFECYCLE_POI_TYPES: frozenset[PoiType] = frozenset(
    {
        PoiType.EQUAL_HIGHS_LIQUIDITY,
        PoiType.EQUAL_LOWS_LIQUIDITY,
        PoiType.PREVIOUS_DAY_HIGH,
        PoiType.PREVIOUS_DAY_LOW,
        PoiType.PREVIOUS_WEEK_HIGH,
        PoiType.PREVIOUS_WEEK_LOW,
        PoiType.PREVIOUS_MONTH_HIGH,
        PoiType.PREVIOUS_MONTH_LOW,
        PoiType.CURRENT_DAY_HIGH,
        PoiType.CURRENT_DAY_LOW,
        PoiType.CURRENT_WEEK_HIGH,
        PoiType.CURRENT_WEEK_LOW,
        PoiType.CURRENT_MONTH_HIGH,
        PoiType.CURRENT_MONTH_LOW,
    }
)

PERIOD_LEVEL_POI_TYPES: frozenset[PoiType] = frozenset(
    {
        PoiType.PREVIOUS_DAY_HIGH,
        PoiType.PREVIOUS_DAY_LOW,
        PoiType.PREVIOUS_WEEK_HIGH,
        PoiType.PREVIOUS_WEEK_LOW,
        PoiType.PREVIOUS_MONTH_HIGH,
        PoiType.PREVIOUS_MONTH_LOW,
        PoiType.CURRENT_DAY_HIGH,
        PoiType.CURRENT_DAY_LOW,
        PoiType.CURRENT_WEEK_HIGH,
        PoiType.CURRENT_WEEK_LOW,
        PoiType.CURRENT_MONTH_HIGH,
        PoiType.CURRENT_MONTH_LOW,
    }
)

CURRENT_PERIOD_POI_TYPES: frozenset[PoiType] = frozenset(
    {
        PoiType.CURRENT_DAY_HIGH,
        PoiType.CURRENT_DAY_LOW,
        PoiType.CURRENT_WEEK_HIGH,
        PoiType.CURRENT_WEEK_LOW,
        PoiType.CURRENT_MONTH_HIGH,
        PoiType.CURRENT_MONTH_LOW,
    }
)
